services:
  postgres:
    image: postgis/postgis:latest
    container_name: biznest_potgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - biznest_db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - biznest_net
  minio:
    image: minio/minio:latest
    container_name: biznest_minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_WEB_PORT}:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"
    networks:
      - biznest_net
    volumes:
      - biznest_data:/data
  redis:
    image: redis:7-alpine
    container_name: biznest_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - biznest_net
    volumes:
      - biznest_redis:/data
    command: redis-server --appendonly yes

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: biznest_redis_insight
    ports:
      - "8001:8001"
    networks:
      - biznest_net
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: redis:${REDIS_PORT}

#  biznest_app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: biznest_app
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#      - minio
#      - redis
#    networks:
#      - biznest_net

volumes:
  biznest_db:
    name: biznest_db
  biznest_data:
    name: biznest_data
  biznest_redis:
    name: biznest_redis

networks:
  biznest_net:
    driver: bridge
    name: biznest_net