/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface AnalyzeRequest {
  /**
     * @minLength 1
     * @maxLength 1000
     */
  question: string;
}
