/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { AuditLogResponseMeta } from './auditLogResponseMeta';

export interface AuditLogResponse {
  id: string;
  user_id: string | null;
  city_id: string | null;
  action: string | null;
  meta: AuditLogResponseMeta;
  created_at: string;
}
