/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface AuthResponse {
  id: string;
  email: string;
  full_name: string;
  access_token: string;
  refresh_token: string;
  token_type?: string;
  expires_in: number;
}
