/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { CityResponseBoundary } from './cityResponseBoundary';

export interface CityResponse {
  id: string;
  name: string;
  province: string | null;
  region: string | null;
  province_id: string | null;
  pmtile_url: string | null;
  boundary: CityResponseBoundary;
  created_at: string;
}
