/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface CityStatsResponse {
  city_id: string;
  hazard_count: number;
  zoning_count: number;
  establishment_count: number;
  alert_count: number;
}
