/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { CityGeometryResponseBoundary } from './cityGeometryResponseBoundary';

/**
 * Standalone geometry-only response — fetched separately and cached independently.
 */
export interface CityGeometryResponse {
  id: string;
  boundary: CityGeometryResponseBoundary;
}
