/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

/**
 * City metadata — never includes geometry. Fetch geometry via /geometry endpoint.
 */
export interface CityResponse {
  id: string;
  name: string;
  province: string | null;
  region: string | null;
  province_id: string | null;
  pmtile_url: string | null;
  created_at: string;
}
