/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface CityUpdate {
  name?: string | null;
  province?: string | null;
  region?: string | null;
}
