/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface EstablishmentUpdate {
  name?: string | null;
  category?: string | null;
  latitude?: number | string | null;
  longitude?: number | string | null;
}
