/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface EstablishmentResponse {
  id: string;
  city_id: string;
  name: string | null;
  category: string | null;
  latitude: string | null;
  longitude: string | null;
  owner_id: string | null;
  created_at: string;
}
