/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { HazardAreaUpdateGeometry } from './hazardAreaUpdateGeometry';

export interface HazardAreaUpdate {
  hazard_type?: string | null;
  severity?: number | null;
  geometry?: HazardAreaUpdateGeometry;
}
