/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { HazardAreaCreateGeometry } from './hazardAreaCreateGeometry';

export interface HazardAreaCreate {
  hazard_type?: string | null;
  scenario?: string | null;
  geometry?: HazardAreaCreateGeometry;
}
