/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

/**
 * List/get response — geometry excluded (use pmtile_url for rendering).
 */
export interface HazardAreaSummary {
  id: string;
  province_id: string;
  hazard_type: string | null;
  scenario: string | null;
  pmtile_url: string | null;
  created_by: string | null;
  created_at: string;
}
