/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { HazardAreaResponseGeometry } from './hazardAreaResponseGeometry';

/**
 * Hazard area with geometry — for the /geometry endpoint.
 */
export interface HazardAreaResponse {
  id: string;
  city_id: string;
  hazard_type: string | null;
  scenario: string | null;
  severity: number | null;
  pmtile_url: string | null;
  geometry?: HazardAreaResponseGeometry;
  created_by: string | null;
  created_at: string;
}
