/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface InvestorSubscriptionUpdate {
  plan_id?: string | null;
  expires_at?: string | null;
}
