/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface InvestorCityAccessResponse {
  id: string;
  user_id: string;
  city_id: string;
  granted_at: string;
}
