/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { SubscriptionPlanResponse } from './subscriptionPlanResponse';

export interface InvestorSubscriptionResponse {
  id: string;
  user_id: string;
  plan_id: string;
  plan: SubscriptionPlanResponse;
  created_at: string;
  expires_at: string | null;
}
