/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface LguAssignmentResponse {
  id: string;
  user_id: string;
  city_id: string;
  created_at: string;
}
