/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface LguInviteResponse {
  message: string;
  magic_link: string;
  city_id: string;
  expires_at: string;
}
