/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface LguRegisterRequest {
  token: string;
  email: string;
  /**
     * @minLength 2
     * @maxLength 100
     */
  full_name: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
}
