/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface LguRegisterRequest {
  token: string;
  email: string;
  /**
     * @minLength 3
     * @maxLength 50
     */
  username: string;
  /** @minLength 6 */
  password: string;
}
