/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export type ListCitiesCitiesGetParams = {
/**
 * Include boundary GeoJSON (expensive — omit for name-only lists)
 */
include_geometry?: boolean;
};
