/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface PresignedUrlResponse {
  file_id: string;
  /** MinIO presigned URL (valid for 1 hour) */
  presigned_url: string;
  /** URL expiration time in seconds (default 3600) */
  expires_in_seconds: number;
}
