/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export type RegenerateHazardPmtilesCitiesCityIdHazardsRegeneratePmtilesPostParams = {
/**
 * flood | landslide | storm_surge | debris_flow | faultline
 */
hazard_type: string;
/**
 * 5yr | 25yr | 100yr | ssa1-ssa4 | null for faultlines
 */
scenario?: string | null;
};
