/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export type RegisterRequestRoleName = typeof RegisterRequestRoleName[keyof typeof RegisterRequestRoleName];


export const RegisterRequestRoleName = {
  investor: 'investor',
  lgu_admin: 'lgu_admin',
} as const;
