/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionResponse } from './permissionResponse';

export interface RoleWithPermissionsResponse {
  id: string;
  name: string;
  created_at: string;
  permissions?: PermissionResponse[];
}
