/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface SavedLocationResponse {
  id: string;
  user_id: string;
  city_id: string | null;
  name: string | null;
  latitude: string | null;
  longitude: string | null;
  created_at: string;
}
