/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface SubscriptionPlanResponse {
  id: string;
  name: string;
  max_cities: number | null;
  created_at: string;
}
