/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export type ZoneType = typeof ZoneType[keyof typeof ZoneType];


export const ZoneType = {
  residential: 'residential',
  commercial: 'commercial',
  industrial: 'industrial',
  agriculture: 'agriculture',
} as const;
