/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface ZoningPmtilesResponse {
  /** Presigned MinIO URL for city-level zoning PMTile */
  pmtile_url: string;
  /** MinIO object key for city-level zoning PMTile */
  object_key: string;
}
