/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { ZoningAreaResponseGeometry } from './zoningAreaResponseGeometry';

export interface ZoningAreaResponse {
  id: string;
  city_id: string;
  zone_type: string | null;
  geometry: ZoningAreaResponseGeometry;
  created_by: string | null;
  created_at: string;
}
