/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface ZoningPmtilesResponse {
  pmtile_url: string;
  object_key: string;
}
