/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Zone geometry for this zone
 */
export type ZoningAreaUpdateGeometry = { [key: string]: unknown } | null;
