/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { ZoneType } from './zoneType';
import type { ZoningAreaUpdateGeometry } from './zoningAreaUpdateGeometry';

export interface ZoningAreaUpdate {
  /** Zone type for this zone */
  zone_type?: ZoneType | null;
  /** Severity classification 1–5 */
  severity?: number | null;
  /** Zone geometry for this zone */
  geometry?: ZoningAreaUpdateGeometry;
}
