/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { ZoningAreaResponse } from './zoningAreaResponse';

export interface ZoningProcessResponse {
  zones_created: number;
  skipped_zones: number;
  pmtile_url: string | null;
  zones: ZoningAreaResponse[];
}
