/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { GroundControlPoint } from './groundControlPoint';

export interface ZoningImageProcessRequest {
  file_id: string;
  gcps: GroundControlPoint[];
  n_colors?: number;
  min_area_px?: number;
}
