/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { ZoningAreaUpdateGeometry } from './zoningAreaUpdateGeometry';

export interface ZoningAreaUpdate {
  zone_type?: string | null;
  geometry?: ZoningAreaUpdateGeometry;
}
