/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { ZoningAreaCreateGeometry } from './zoningAreaCreateGeometry';

export interface ZoningAreaCreate {
  city_id: string;
  zone_type?: string | null;
  geometry?: ZoningAreaCreateGeometry;
}
