/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { ZoningAreaResponseGeometry } from './zoningAreaResponseGeometry';

/**
 * Geometry-only response — id, city_id, geometry. Enables separate caching from metadata.
 */
export interface ZoningAreaGeometryResponse {
  id: string;
  city_id: string;
  geometry?: ZoningAreaResponseGeometry;
}
