/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { ZoneType } from './zoneType';
import type { ZoningAreaCreateGeometry } from './zoningAreaCreateGeometry';

export interface ZoningAreaCreate {
  /** City Id */
  city_id: string;
  /** Zone type for this zone */
  zone_type?: ZoneType | null;
  /** Zone geometry for this zone */
  geometry?: ZoningAreaCreateGeometry;
}
